version: "3.8"
services:
  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend


networks:
  app-network:
    driver: bridge
